CREATE USER testuser IDENTIFIED BY 123 
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT;
-- Grant/Revoke role privileges 
GRANT CONNECT TO testuser WITH admin OPTION;
GRANT RESOURCE TO testuser WITH admin OPTION;
-- Grant/Revoke system privileges 
GRANT CREATE PROCEDURE TO testuser WITH admin OPTION;
GRANT CREATE SESSION TO testuser WITH admin OPTION;
GRANT CREATE SEQUENCE  TO testuser WITH admin OPTION;
GRANT CREATE SYNONYM   TO testuser WITH admin OPTION;
GRANT CREATE PUBLIC SYNONYM TO testuser WITH admin OPTION;
GRANT CREATE TABLE TO testuser WITH admin OPTION;
GRANT CREATE TRIGGER TO testuser WITH admin OPTION;
GRANT CREATE VIEW TO testuser WITH admin OPTION;

CONNECT testuser/123@orcl;

CREATE TABLE Viddilenya 
(
   NvID    NUMBER GENERATED by default on null as IDENTITY,
   Nazva  VARCHAR2(500),              
   Glav  VARCHAR2(500),              
   Nomer NUMBER,  
   Adres  VARCHAR2(500)
);

INSERT INTO Viddilenya(Nazva, Glav, Nomer, Adres) 
VALUES('City Hospital','Dr. Smith',71345,'123 Main Street, Cityville');
INSERT INTO Viddilenya(Nazva, Glav, Number, Adress) 
VALUES('Central Clinic','Dr. Johnson',14567,'456 Elm Street, Centertown');
INSERT INTO Viddilenya(Nazva, Glav, Number, Adress) 
VALUES('Sunset Medical Center','Dr. Davis',39937,'789 Oak Street, Sunset Valley');
INSERT INTO Viddilenya(Nazva, Glav, Number, Adress) 
VALUES('Hillside Hospital','Dr. Wilson',32367,'101 Pine Street, Hillside');
INSERT INTO Viddilenya(Nazva, Glav, Number, Adress) 
VALUES('Riverfront Health Center','Dr. Miller',38112,'202 Cedar Street, Riverfront');
COMMIT;

CREATE TABLE Pacient 
(
   PID    NUMBER GENERATED by default on null as IDENTITY,
   Name   VARCHAR2(500),                       
   Prizv  VARCHAR2(500),                       
   dBirth  VARCHAR2(500),
   Pol   NUMBER, 
   NvID   NUMBER NOT NULL,  
   Adres  VARCHAR2(500),
   Phone  NUMBER,
);

INSERT INTO Pacient(Name, Prizv, dBirth, Pol, NvID, Adres,Phone) VALUES('Gary','Sonald','16/03/2000',1,1,'Cedar St.',380952824243);
INSERT INTO Pacient(Name, Prizv, dBirth, Pol, NvID, Adres, Phone) 
VALUES('Alice', 'Johnson', '10/05/1995', 0, 2, 'Maple Ave.', 380951234567);
INSERT INTO Pacient(Name, Prizv, dBirth, Pol, NvID, Adres, Phone) 
VALUES('Bob', 'Smith', '25/09/1988', 1, 3, 'Oak St.', 380961234567);
INSERT INTO Pacient(Name, Prizv, dBirth, Pol, NvID, Adres, Phone) 
VALUES('Eva', 'Brown', '03/12/1992', 0, 1, 'Pine Rd.', 380971234567);
INSERT INTO Pacient(Name, Prizv, dBirth, Pol, NvID, Adres, Phone) 
VALUES('Michael', 'Davis', '21/07/1980', 1, 2, 'Elm St.', 380981234567);
INSERT INTO Pacient(Name, Prizv, dBirth, Pol, NvID, Adres, Phone) 
VALUES('Sophia', 'Lee', '14/11/1998', 0, 3, 'Cypress Blvd.', 380991234567);
COMMIT;

CREATE TABLE Doctor
(
   LID    NUMBER GENERATED by default on null as IDENTITY,
   NvID   NUMBER NOT NULL,     
   Name   VARCHAR2(500),                       
   Prizv  VARCHAR2(500),                       
   dBirth  VARCHAR2(500),
   Pol   NUMBER,
   Speciality  VARCHAR2(500),
   Adres  VARCHAR2(500),
   Phone  NUMBER,
);

INSERT INTO Doctor(Name,Prizv,dBirth,Pol,Speciality,Adres,Phone) 
VALUES('Vasya','Sorter','25/05/2001',1,'Eye Doctor','Markovo st.',380958388383);
INSERT INTO Doctor(NvID, Name, Prizv, dBirth, Pol, Speciality, Adres, Phone) 
VALUES(1, 'John', 'Doe', '10/02/1975', 1, 'Cardiologist', 'Oak St.', 380951234567);

INSERT INTO Doctor(NvID, Name, Prizv, dBirth, Pol, Speciality, Adres, Phone) 
VALUES(2, 'Alice', 'Smith', '15/07/1982', 0, 'Neurologist', 'Elm St.', 380961234567);

INSERT INTO Doctor(NvID, Name, Prizv, dBirth, Pol, Speciality, Adres, Phone) 
VALUES(3, 'Michael', 'Johnson', '20/03/1978', 1, 'Pediatrician', 'Maple Ave.', 380971234567);

INSERT INTO Doctor(NvID, Name, Prizv, dBirth, Pol, Speciality, Adres, Phone) 
VALUES(1, 'Emily', 'Davis', '05/11/1985', 0, 'Dermatologist', 'Pine Rd.', 380981234567);

INSERT INTO Doctor(NvID, Name, Prizv, dBirth, Pol, Speciality, Adres, Phone) 
VALUES(2, 'Daniel', 'Lee', '12/09/1989', 1, 'Orthopedic Surgeon', 'Cypress Blvd.', 380991234567);

INSERT INTO Doctor(NvID, Name, Prizv, dBirth, Pol, Speciality, Adres, Phone) 
VALUES(3, 'Sophia', 'Brown', '28/06/1983', 0, 'Oncologist', 'Cedar St.', 380958388383);

COMMIT;

CREATE TABLE IllStory
( 
   dStart VARCHAR2(100), 
   CONSTRAINT PID FOREIGN KEY (PID) REFERENCES Patient(PID),
   CONSTRAINT LID FOREIGN KEY (LID) REFERENCES Doctor(LID),
   dEnd VARCHAR2(100), 
   Symptoms VARCHAR2(300),
);

INSERT INTO IllStory(PID, LID, dStart, dEnd, Symptoms) VALUES(2, 3, '24/06/2002', '24/07/2002', 'Cough');
INSERT INTO IllStory(PID, LID, dStart, dEnd, Symptoms) VALUES(1, 2, '15/08/2002', '05/09/2002', 'Fever');
INSERT INTO IllStory(PID, LID, dStart, dEnd, Symptoms) VALUES(3, 1, '03/03/2002', '18/03/2002', 'Headache');
INSERT INTO IllStory(PID, LID, dStart, dEnd, Symptoms) VALUES(2, 3, '10/11/2001', '30/11/2001', 'Fatigue');
INSERT INTO IllStory(PID, LID, dStart, dEnd, Symptoms) VALUES(1, 1, '20/05/2002', '05/06/2002', 'Sore throat');
INSERT INTO IllStory(PID, LID, dStart, dEnd, Symptoms) VALUES(3, 2, '08/09/2002', '18/09/2002', 'Nausea');
INSERT INTO IllStory(PID, LID, dStart, dEnd, Symptoms) VALUES(2, 1, '12/02/2002', '28/02/2002', 'Chest pain');
INSERT INTO IllStory(PID, LID, dStart, dEnd, Symptoms) VALUES(1, 3, '01/04/2002', '10/04/2002', 'Shortness of breath');
COMMIT;
